columns:
- MONTH: int64
- DAY_OF_MONTH: int64
- DAY_OF_WEEK: int64
- UNIQUE_CARRIER: object
- DISTANCE: float64
- ORIGIN_CITY_TIME_ZONE: object
- DEST_CITY_TIME_ZONE: object
- SCHD_ARR_TIME_UTC_MINUTES: int64
- EXPECTED_DURATION: int64
- NEW_ORIGIN: object
- NEW_DEST: object
- ARR_DELAY_CLS: int64
numerical_columns:
- DISTANCE
- SCHD_ARR_TIME_UTC_MINUTES
- EXPECTED_DURATION
